trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
  displayName: 'Run a multi-line script'

- task: InstallSSHKeyTesting1@0
  inputs:
    knownHostsEntry: 'firstHost secondHost thirdHost'
    sshPublicKey: 'sshPublicKeyEmpty'
    sshKeySecureFile: 'sshKeySecureFileEmpty'